"""empty message

Revision ID: 44d0ca8a27d0
Revises: 2bf8415a1610
Create Date: 2023-03-20 15:50:15.499325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d0ca8a27d0'
down_revision = '2bf8415a1610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_left_dir')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_left_dir', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
